apiVersion: v2
name: querydoc
description: Document query MCP server for kagent
type: application
version: 0.0.1
appVersion: 1.1.10
sources:
  - https://github.com/kagent-dev/doc2vec
  - https://github.com/kagent-dev/kagent