apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maduro.fullname" . }}-controller
  namespace: {{ include "maduro.namespace" . }}
  labels:
    {{- include "maduro.labels" . | nindent 4 }}
