apiVersion: v1
kind: Service
metadata:
  name: {{ include "maduro.fullname" . }}-controller
  namespace: {{ include "maduro.namespace" . }}
  labels:
    {{- include "maduro.controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.ports.port }}
      targetPort: {{ .Values.controller.service.ports.targetPort }}
      protocol: TCP
      name: controller
  selector:
    {{- include "maduro.controller.selectorLabels" . | nindent 4 }}
