apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maduro.fullname" . }}-ui
  namespace: {{ include "maduro.namespace" . }}
  labels:
    {{- include "maduro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      {{- include "maduro.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.ui.podAnnotations | default .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "maduro.ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "maduro.fullname" . }}-ui
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{- $reg := .Values.ui.image.registry | default .Values.registry -}}{{- if $reg -}}{{ $reg }}/{{- end -}}{{ .Values.ui.image.repository }}:{{ coalesce .Values.tag .Values.ui.image.tag .Chart.Version }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy | default .Values.imagePullPolicy }}
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://{{ include "maduro.fullname" . }}-controller.{{ include "maduro.namespace" . }}.svc.cluster.local:{{ .Values.controller.service.ports.port }}/api"
            {{- with .Values.ui.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.ui.service.ports.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 1
            initialDelaySeconds: 1
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            failureThreshold: 3