apiVersion: v1
kind: Service
metadata:
  name: {{ include "maduro.fullname" . }}-ui
  namespace: {{ include "maduro.namespace" . }}
  labels:
    {{- include "maduro.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.ports.port }}
      targetPort: {{ .Values.ui.service.ports.targetPort }}
      protocol: TCP
      name: ui
  selector:
    {{- include "maduro.ui.selectorLabels" . | nindent 4 }}
